name: Reminder
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - run: do-the-thing.sh
      - uses: gr2m/set-cron-schedule-action@v2
        with:
          token: ${{ secrets.PAT_WITH_WORKFLOW_SCOPE }}
          cron: |
            0 10 * * 2
            0 15 * * 4
          # optional: set workflow id or file name
          workflow: my-workflow.yml
          # optional: Defaults to "ci($WORKFLOW_NAME): update cron schedule: $CRON_EXPRESSIONS".
          #           $WORKFLOW_NAME and $CRON_EXPRESSIONS will be replaced.
          message: "update cron for next reminder to do the thing"
